version: '3.1'

services:
  mongo:
    image: mongo:4
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: app
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
  loadr:
    container_name: loadr
    build:
      context: .
      dockerfile: ./cmd/app/Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - mongo
      - redis
    restart: always
    environment:
      BACKEND: 0.0.0.0:8080
      CLIENTS: 0.0.0.0:9090
      REDIS: redis:6379
      MONGO: mongo:27017
      MONGO_USER: mongouser
      MONGO_PASS: mongopass
      MONGO_DATABASE: admin
      MONGO_COLLECTION: loadr